package ru.ibs.updateservice;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "UpdateService", targetNamespace = "http://www.ibs.ru/UpdateService/")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.WRAPPED, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface UpdateService {

  /**
   * Java representation of web method [Update].
   */
  @javax.jws.WebMethod(operationName = "Update", action = "http://www.ibs.ru/UpdateService/Update")
  @javax.xml.ws.RequestWrapper(localName = "Update", targetNamespace = "http://www.ibs.ru/UpdateService/", className = "ru.ibs.updateservice.Update")
  @javax.xml.ws.ResponseWrapper(localName = "UpdateResponse", targetNamespace = "http://www.ibs.ru/UpdateService/", className = "ru.ibs.updateservice.UpdateResponse")
  @javax.jws.WebResult(name = "outputData", targetNamespace = "")
  public ru.ibs.updateservice.OutputData update(@javax.jws.WebParam(name = "obsoleteData", targetNamespace = "") byte[] obsoleteData, @javax.jws.WebParam(name = "obsoleteDataType", targetNamespace = "") java.lang.String obsoleteDataType, @javax.jws.WebParam(name = "actualData", targetNamespace = "") byte[] actualData, @javax.jws.WebParam(name = "actualDataType", targetNamespace = "") java.lang.String actualDataType, @javax.jws.WebParam(name = "keyColumnMapping", targetNamespace = "") java.util.List<ru.ibs.updateservice.IndexMapping> keyColumnMapping, @javax.jws.WebParam(name = "mergeColumnMapping", targetNamespace = "") java.util.List<ru.ibs.updateservice.IndexMapping> mergeColumnMapping, @javax.jws.WebParam(name = "complexKey", targetNamespace = "") java.lang.Boolean complexKey);

}
